exclude_paths:
  - .bundle

directories:
  "test":
    TooManyStatements:
      enabled: false

detectors:
  TooManyMethods:
    max_methods: 20
  TooManyStatements:
    max_statements: 10
  UncommunicativeVariableName:
    accept:
      - e
  UtilityFunction:
    public_methods_only: true
